import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { cn } from '@/lib/utils';
import Link from 'next/link';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={cn(openSans.className, 'overflow-x-hidden')}>
				<Navbar />
				{children}
				<footer className='py-4 text-center text-foreground-light'>
					{/* <span>Made with 💖 by Me © 2023</span> */}
					<span>Powered by Me © {new Date().getFullYear()}</span>
					<span className='mx-2'>•</span>
					<Link href='https://github.com' className='underline'>
						Source Code
					</Link>
				</footer>
			</body>
		</html>
	);
}
